apiVersion: v1
name: titlis-operator
description: "Titlis Operator - reconciliation for SLOs, Tags and Monitors (Datadog)"
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: "SRE Team"
    email: sre@example.com